apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: cert-manager
  namespace: argocd

spec:
  project: default

  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.21.1
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/helm/cert-manager-values.yaml

    - repoURL: https://github.com/rafiquehumdaan-alt/2048-EKS.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
