clusterName: "2048-eks-cluster"

region: "eu-west-2"

vpcId: "vpc-0da550afd49dec985"

serviceAccount:
  create: true
  name: "aws-load-balancer-controller"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::435059220418:role/2048-eks-aws-load-balancer-controller-role"